name: code.my-locus
markdown: redcarpet
encoding: utf-8
port: 4444
basePath: /
imagePath: /images/
static: /static/
permalink: /:categories/:year_:month_:day/:title.html
paginate_path: /page:num
paginate: 10
author: 
 name: code.my-locus
 email : ipenglei03@gmail.com
