name: code.my-locus
markdown: redcarpet
encoding: utf-8
port: 4444
basePath: //geekpeng.github.io
imagePath: /images
static: /static
permalink: /:categories/:year_:month_:day/:title.html
author: 
 name: geek03
 email : ipenglei03@gmail.com
