name: geekeach
markdown: redcarpet
pygments: true
encoding: utf-8
port: 4444
basePath: //www.geekeach.com
imagePath: //www.geekeach.com/images
static: /static
permalink: /:categories/:year_:month_:day/:title.html
auther: 
 name: geek03
 email : geekeach@gmail.com
