name: geekeach
markdown: redcarpet
pygments: true
basePath: //www.geekpeng.github.io
static: /static
permalink: /:categories/:year_:month_:day/:title.html
auther: 
 name: ipenglei
 email : ipenglei@gmail.com
